module Datadog
  module AppSec
    module WAF
      type input = nil | bool | ::String | ::Symbol | ::Integer | ::Float | ::Array[input] | ::Hash[input, input]
      type output = nil | bool | ::String | ::Integer | ::Float | ::Array[output] | ::Hash[::String, output]
      type known_addresses = ::Array[::String]

      self.@logger: ::Logger

      self.@log_callback: LibDDWAF::ddwaf_log_cb

      def self?.version: () -> ::String

      def self?.log_callback: (LibDDWAF::ddwaf_log_level, ::String, ::String, ::Integer, ::FFI::Pointer, ::Integer) -> void

      def self?.logger: () -> ::Logger

      def self?.logger=: (::Logger logger) -> void
    end
  end
end
