inherit_from: .rubocop_todo.yml

Metrics/AbcSize:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/datadog/**/*_spec.rb"

# Requires Ruby 3.1
Style/HashSyntax:
  EnforcedShorthandSyntax: never
