inherit_from: .rubocop_todo.yml

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/datadog/appsec/waf_spec.rb'

# Requires Ruby 3.1
Style/HashSyntax:
  EnforcedShorthandSyntax: never
