# This file is used to ignore specific rules for specific files or directories.
---
ignore:
  # After quite some discussion on the team, we decided to make an exception to the
  # "standard-isn't-supposed-to-be-configured" thing to allow for trailing comma, see
  # https://github.com/standardrb/standard/issues/611 for a discussion
  - "**/**":
      - Style/TrailingCommaInArguments
      - Style/TrailingCommaInArrayLiteral
      - Style/TrailingCommaInHashLiteral
      - Style/StringLiterals
      # These complain about strings that contain interpolation, demanding
      # additional conversion to symbol which is extra overhead:
      # https://github.com/rubocop/rubocop/issues/13955
      - Performance/StringIdentifierArgument

  # This disables standardrb.
  - spec/**/*
