module Datadog
  module AppSec
    module WAF
      class Error < StandardError
      end

      class InstanceFinalizedError < Error
      end

      class ConversionError < Error
      end

      class LibDDWAFError < Error
        attr_reader diagnostics: WAF::output

        def initialize: (::String msg, ?diagnostics: WAF::output?) -> void
      end
    end
  end
end
