name: Lint
on:
  - push

jobs:
  style-check:
    name: Style check
    runs-on: ubuntu-24.04
    container:
      image: ruby:3.3
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Bundle
        run: bundle install

      - name: Run standardrb
        run: standardrb

  type-check:
    name: Type check
    runs-on: ubuntu-24.04
    container:
      image: ruby:3.3
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Bundle
        run: bundle install

      - name: Run Steep
        run: bundle exec rake steep:check
