name: Lint
on:
  - push

jobs:
  style-check:
    name: Style check
    runs-on: ubuntu-20.04
    container:
      image: ruby:3.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bundle
        run: |
          bundle install
      - name: Run Rubocop
        run: |
          bundle exec rubocop -D
  type-check:
    name: Type check
    runs-on: ubuntu-20.04
    container:
      image: ruby:3.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bundle
        run: |
          bundle install
      - name: Run Steep
        run: |
          bundle exec steep check --severity-level=error
