name: Package
on:
  - push

jobs:
  test-rake-binary:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        ruby: ["3.3", "9.4"]
        libc: [gnu, musl]
        include:
          - os: ubuntu-24.04
            platform: x86_64-linux:llvm
          - os: ubuntu-24.04-arm
            platform: aarch64-linux:llvm
          - ruby: 3.3
            jruby: false
          - ruby: 9.4
            jruby: true
        exclude:
          - ruby: 9.4
            libc: musl

    name: Test gem build (${{ matrix.jruby == true && 'Jruby' || 'Ruby'}} ${{ matrix.ruby }}, ${{ matrix.os }}, ${{ matrix.libc }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Build docker image
        id: build-image
        uses: ./.github/actions/docker-build-ruby
        with:
          ruby-version: ${{ matrix.ruby }}
          libc: ${{ matrix.libc }}
          jruby: ${{ matrix.jruby }}

      - name: Bundle install
        run: ${{ steps.build-image.outputs.run-cmd }} bundle install

      - name: Build platform-specific binary gem
        run: ${{ steps.build-image.outputs.run-cmd }} bundle exec rake libddwaf:build[${{ matrix.platform }}]

      - name: List artifact files
        run: find .
        working-directory: pkg

      - name: Install platform-specific gem
        run: ${{ steps.build-image.outputs.run-cmd }} gem install --verbose pkg/*.gem

      - name: Run smoke test
        run: ${{ steps.build-image.outputs.run-cmd }} ruby -r 'libddwaf' -e 'p Datadog::AppSec::WAF::LibDDWAF.ddwaf_get_version'

      - name: Uninstall platform-specific gem
        run: ${{ steps.build-image.outputs.run-cmd }} gem uninstall --all --force --verbose libddwaf

      - name: Remove artifact files
        run: ${{ steps.build-image.outputs.run-cmd }} rm -f pkg/*.gem

      - name: Build generic gem
        run: ${{ steps.build-image.outputs.run-cmd }} bundle exec rake libddwaf:buildx

      - name: List artifact files
        run: find .
        working-directory: pkg

      - name: Install generic gem
        run: ${{ steps.build-image.outputs.run-cmd }} gem install --verbose pkg/*.gem

      - name: Run smoke test
        run: ${{ steps.build-image.outputs.run-cmd }} ruby -r 'libddwaf' -e 'p Datadog::AppSec::WAF::LibDDWAF.ddwaf_get_version'

  test-rake-binary-on-darwin:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, macos-15-large]
        include:
          - os: macos-15
            platform: arm64-darwin
          - os: macos-15-large
            platform: x86_64-darwin

    name: Test gem build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Bundle
        run: bundle install

      - name: Build binary gem
        run: bundle exec rake libddwaf:build[${{ matrix.platform }}]

      - name: Install gem
        run: gem install --verbose pkg/*.gem

      - name: Run smoke test
        run: ruby -r 'libddwaf' -e 'p Datadog::AppSec::WAF::LibDDWAF.ddwaf_get_version'

      - name: Uninstall platform-specific gem
        run: gem uninstall --all --force --verbose libddwaf

      - name: Remove artifact files
        run: rm -f pkg/*.gem

      - name: Build generic gem
        run: bundle exec rake libddwaf:buildx

      - name: List artifact files
        run: find .
        working-directory: pkg

      - name: Install generic gem
        run: gem install --verbose pkg/*.gem

      - name: Run smoke test
        run: ruby -r 'libddwaf' -e 'p Datadog::AppSec::WAF::LibDDWAF.ddwaf_get_version'
